:zzz: Update the s2i run script
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

diff --git a/s2i/bin/run b/s2i/bin/run
--- a/s2i/bin/run
+++ b/s2i/bin/run
@@ -13,21 +13,21 @@ echo "run...."
 command_exists () { type "$1" &> /dev/null ; }
 file_exists () { test -f $1 ; }
 folder_exists () { test -d $1 ; }
-MY_EXIT_1() {  exit 1; }
+MY_EXIT_1() { echo "ERROR:variable not set" && exit 1; }
 MY_RETURN_1() {  return 1; }
 MY_RETURN_0() {  return 0; }
 env_check () {
   exit_function=MY_RETURN_0;
   # If exit function is passed as $2 use it.
-  if [[ ! -z "$2" ]];then exit_function=$2 ;fi 
+  if [[ ! -z "$2" ]];then exit_function=$2 ;fi
   if [ $# -eq 0 ];then printf "No arguments supplied. \nUsage:\n env_check \"ENV_NAME\" [\"exit_function\"]\n" && $exit_function;fi
   param=$1;
   # The exclamation mark makes param to get the value of the variable with that name.
-  if [[ -z "${!param}" ]];then echo "$1 is undefined" && $exit_function; else echo "$1 = "${!param} ;fi 
+  if [[ -z "${!param}" ]];then echo "$1 is undefined" && $exit_function; else echo "$1 = "${!param} ;fi
 }
 check_oauth_scope() {
   # check to see if X-OAuth-Scopes has repo
-  curl --silent -i -H "Authorization: token $GIT_TOKEN" https://api.github.com/rate_limit | 
+  curl --silent -i -H "Authorization: token $GIT_TOKEN" https://api.github.com/rate_limit |
     grep "X-OAuth-Scopes:" | tr -d ":" | awk -v N=$2 '{print $2}'                                   # Pluck JSON value
 }
 
@@ -80,9 +80,17 @@ env_check TEST_WHEEL_FILE MY_EXIT_1
 env_check GIT_RELEASE_REPO MY_EXIT_1
 env_check HOME
 
-OUATH_SCOPE=$(check_oauth_scope)
-env_check OUATH_SCOPE
+if [[ $LOCAL_BUILD = "n" ]]; then
+	OAUTH_SCOPE=$(check_oauth_scope)
+	echo "OAUTH_SCOPE uses GIT_TOKEN"
+	env_check OAUTH_SCOPE
+fi
 echo "============================================"
+
+
+TEST_CMD="import tensorflow as tf ; a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a') ; \
+	b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b') ; c = tf.matmul(a, b) ; \
+	sess = tf.Session(config=tf.ConfigProto(log_device_placement=True)) ;print(sess.run(c))"
 
 BUILD_TOOLS_DIR="/build_tools"
 env_check BUILD_TOOLS_DIR
@@ -152,12 +160,12 @@ ls -l $JAVA_HOME
 
 ### Setup Bazel
 cd /workspace
-if command_exists bazel ; then 
-	echo "bazel command exists."; 
-else 
-	echo "bazel doesnt exists" && cd /tf/tools/ && 
-	./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh --user && 
-	export PATH=$HOME/bin:$PATH && bazel && echo "PATH = "$PATH ; 
+if command_exists bazel ; then
+	echo "bazel command exists.";
+else
+	echo "bazel doesnt exists" && cd /tf/tools/ &&
+	./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh --user &&
+	export PATH=$HOME/bin:$PATH && bazel && echo "PATH = "$PATH ;
 fi
 
 ### git clone tf and test
@@ -183,33 +191,11 @@ git clone --branch=$TF_GIT_BRANCH --depth=1 https://github.com/tensorflow/servin
 ### TODO NO GPU support yet
 ###########################
 env_check TF_NEED_CUDA
-if [ $TF_NEED_CUDA = "1" ]; then 
+if [ $TF_NEED_CUDA = "1" ]; then
 	echo "####################################"
 	echo "      CUDA BUILD TODO.....       	  "
 	echo "####################################"
-fi 
-
-
-
-
-# Naming the directory according to the naming convention
-OSVER=$(. /etc/os-release;echo $ID$VERSION_ID)
-for varname in ${!TF_NEED_*}; do
-	if [ "$varname" = "TF_GIT_BRANCH" ]; then
-        continue
-    fi
-    if [ "${!varname}" = "1" ]; then
-        WORD=$(echo "${varname//TF_NEED_}" | tr '[:upper:]' '[:lower:]')
-        echo $WORD
-        unset "${varname}"
-    elif [ "${!varname}" = "0" ]; then
-        WORD=$(echo "${varname//TF_NEED_}" | tr '[:upper:]' '[:lower:]')
-        echo $WORD
-        unset "${varname}"
-    fi
-done
-TENSORFLOW_BUILD_DIR_NAME=$OSVER/${TF_GIT_BRANCH//r}
-
+fi
 
 
 # /workspace/bins is final location of binaries
@@ -243,14 +229,14 @@ else
 	# && FINAL_FILE=$(basename `ls /tmp/tensorflow_serving_api*`)
 	if [ -e /workspace/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server ]
 	then
-		## bazel build is success 
+		## bazel build is success
 		## cleanup old
 		echo "File tensorflow_model_server exists."
 		cd /workspace
 		env_check CUSTOM_BUILD_2
 		eval "$CUSTOM_BUILD_2" 2>&1 | tee -a /workspace/build.log ; test ${PIPESTATUS[0]} -eq 0
 		if (( $? )); then
-		    echo "####################################"
+		  echo "####################################"
 			echo "      CUSTOM_BUILD_2  ERROR!!     	  "
 			echo "####################################"
 			$MY_EXIT_1
@@ -282,7 +268,7 @@ else
 				else
 					GIT_TAG="$TF_FILE_NAME-${TF_GIT_BRANCH}-cpu-$(date +%Y-%m-%d_%H%M%S)"
 				fi
-				RELEASE_NOTES=$(python $BUILD_TOOLS_DIR/utils.py /workspace/bins/build_info.json) 
+				RELEASE_NOTES=$(python $BUILD_TOOLS_DIR/utils.py /workspace/bins/build_info.json)
 				GIT_TOKEN="${GIT_TOKEN}"
 				RELEASE_FILES="$PIP_RELEASE_FOLDER/${BINARY_FILE} /workspace/bins/build_info.yaml /workspace/bins/build_info.json"
 				env_check RELEASE_FILES
@@ -302,14 +288,13 @@ if ls -l  /workspace/build.log; then
 fi
 
 
-### enable HOST_ON_HTTP_SERVER only with deploymentConfig(i.e build-dc.json) and NOT with Jobs. 
+### enable HOST_ON_HTTP_SERVER only with deploymentConfig(i.e build-dc.json) and NOT with Jobs.
 if [[ $HOST_ON_HTTP_SERVER = "y" ]]
 then
 	echo "Starting httpserver to host the binary...\n"
     cd /workspace/
-	if [[ $PYTHON_VERSION = "2.7" ]] ; then 
-		python -m SimpleHTTPServer $PORT ; 
-	else python -m http.server $PORT ; 
+	if [[ $PYTHON_VERSION = "2.7" ]] ; then
+		python -m SimpleHTTPServer $PORT ;
+	else python -m http.server $PORT ;
 	fi
 fi
-
